server.port=${SERVER_PORT:8085}
server.servlet.context-path=/user
server.forward-headers-strategy=framework

spring.application.name=user
spring.threads.virtual.enabled=true
management.tracing.sampling.probability=1.0
management.endpoints.web.exposure.include=health,info
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.tags.application=${spring.application.name}

logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:54320}/${POSTGRES_DB:utm}
spring.datasource.username=${POSTGRES_USER:admin}
spring.datasource.password=${POSTGRES_PASSWORD:admin}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# OpenAPI / Swagger UI
springdoc.swagger-ui.path=/swagger-ui
springdoc.packagesToScan=com.utm.user
cors.allowed-origins=*
