services:
  nginx:
    image: nginx:1.27.2
    restart: unless-stopped
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/configuration/custom_proxy_settings.conf:/etc/nginx/conf.d/custom_proxy_settings.conf
    ports:
      - "${NGINX_PORT:-8081}:80"
    depends_on:
      - drone
      - hub
      - flight
      - airspace
      - telemetry
      - backoffice-bff
      - swagger-ui
      - identity
    networks:
      - utm-network

  backoffice-bff:
    build:
      context: .
      dockerfile: ./backoffice-bff/Dockerfile
    image: backoffice-bff:latest
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - KEYCLOAK_URL=http://identity
      - DRONE_SERVICE_URL=http://drone:8085
      - HUB_SERVICE_URL=http://hub:8084
      - FLIGHT_SERVICE_URL=http://flight:8086
      - AIRSPACE_SERVICE_URL=http://airspace:8087
    depends_on:
      - identity
      - drone
      - hub
      - flight
      - airspace
    networks:
      - utm-network

  drone:
    build:
      context: .
      dockerfile: ./drone/Dockerfile
    image: drone:latest
    ports:
      - "8085:8085"
    environment:
      - SERVER_PORT=8085
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=utm_drone
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
      - KEYCLOAK_URL=http://identity
      - HUB_SERVICE_URL=http://hub:8084
    depends_on:
      - postgres
      - hub
    networks:
      - utm-network

  hub:
    build:
      context: .
      dockerfile: ./hub/Dockerfile
    image: hub:latest
    ports:
      - "8084:8084"
    environment:
      - SERVER_PORT=8084
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=utm_hub
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
      - KEYCLOAK_URL=http://identity
    depends_on:
      - postgres
    networks:
      - utm-network

  flight:
    build:
      context: .
      dockerfile: ./flight/Dockerfile
    image: flight:latest
    ports:
      - "8086:8086"
    environment:
      - SERVER_PORT=8086
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=utm_flight
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
      - KEYCLOAK_URL=http://identity
      - DRONE_SERVICE_URL=http://drone:8085
      - HUB_SERVICE_URL=http://hub:8084
      - AIRSPACE_SERVICE_URL=http://airspace:8087
    depends_on:
      - postgres
      - drone
      - hub
      - airspace
    networks:
      - utm-network

  airspace:
    build:
      context: .
      dockerfile: ./airspace/Dockerfile
    image: airspace:latest
    ports:
      - "8087:8087"
    environment:
      - SERVER_PORT=8087
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=utm_airspace
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
      - KEYCLOAK_URL=http://identity
      - HUB_SERVICE_URL=http://hub:8084
    depends_on:
      - postgres
      - hub
    networks:
      - utm-network

  telemetry:
    build:
      context: .
      dockerfile: ./telemetry/Dockerfile
    image: telemetry:latest
    ports:
      - "8089:8089"
    environment:
      - SERVER_PORT=8089
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=utm_telemetry
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
      - KEYCLOAK_URL=http://identity
    depends_on:
      - postgres
    networks:
      - utm-network

  swagger-ui:
    image: swaggerapi/swagger-ui:v5.17.14
    ports:
      - "8088:8080"
    environment:
      - BASE_URL=/swagger-ui
      - "URLS=[{ url: '/drone/v3/api-docs', name: 'Drone Service' }, { url: '/hub/v3/api-docs', name: 'Hub Service' }, { url: '/flight/v3/api-docs', name: 'Flight Service' }, { url: '/airspace/v3/api-docs', name: 'Airspace Service' }, { url: '/telemetry/v3/api-docs', name: 'Telemetry Service' }, { url: '/backoffice-bff/v3/api-docs', name: 'Backoffice BFF' }]"
    networks:
      - utm-network

  identity:
    image: quay.io/keycloak/keycloak:26.0.2
    command: 'start-dev --import-realm'
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: ${POSTGRES_USER:-admin}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      KC_HTTP_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - ./identity/realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ./identity/themes/utm/theme:/opt/keycloak/themes
    depends_on:
      - postgres
    networks:
      - utm-network

  postgres:
    image: postgres:16-alpine
    hostname: ${POSTGRES_HOST:-postgres}
    ports:
      - "${POSTGRES_LOCAL_PORT:-54320}:5432"
    volumes:
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
    networks:
      - utm-network

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@utm.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - utm-network

networks:
  utm-network:
    driver: bridge
    name: utm-network

volumes:
  postgres_data:
  pgadmin_data: