server.port=${SERVER_PORT:8082}
server.servlet.context-path=/backoffice-bff
server.forward-headers-strategy=framework

spring.application.name=backoffice-bff
spring.threads.virtual.enabled=true
management.tracing.sampling.probability=1.0
management.endpoints.web.exposure.include=health,info
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.tags.application=${spring.application.name}

logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

# Keycloak / OAuth2 configuration
utm.keycloak.auth-server-url=${KEYCLOAK_URL:http://identity}
utm.keycloak.realm=${KEYCLOAK_REALM:UTM}
utm.keycloak.client-id=${KEYCLOAK_CLIENT_ID:swagger-ui}
utm.keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET:}


# Spring Security OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_URL:http://identity}/realms/${KEYCLOAK_REALM:UTM}

# OpenAPI / Swagger UI
springdoc.swagger-ui.path=/swagger-ui
springdoc.packagesToScan=com.utm.backofficebff
cors.allowed-origins=*
# OpenAPI / Swagger UI OAuth2
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true
springdoc.swagger-ui.oauth.client-id=swagger-ui
springdoc.oauthflow.authorization-url=${KEYCLOAK_AUTH_URL:http://localhost:8080/realms/UTM/protocol/openid-connect/auth}
springdoc.oauthflow.token-url=${KEYCLOAK_TOKEN_URL:http://localhost:8080/realms/UTM/protocol/openid-connect/token}
